### ISSUE TITLE
Add small caps æ and ø

### ISSUE THREAD

**Issue by sigurdhasle** [indestructible-type/Besley#19]
If I download Besley* from https://indestructibletype.com I get an old version (1.8.3) which is useless in Norwegian because of the ø's. If I download from github I get version 2.000 which is equally useless for the same reason. But if I download from Google fonts I get version 2.001 which is perfect! This version is called Besley (without an asterisk) and contains no weight called fatface – but a «black» which looks very similiar. Will you update the fonts – at least in indestructibletype.com?

**Comment by EwonRael** [comment]
I'll work on this.

**Comment by EwonRael** [comment]
done!

**Comment by ctrlcctrlv** [comment]
@sigurdhasle opened #32 which was quite rude and also a duplicate so I closed it but you forgot to add the substitutions to the lookup. I'll open a PR for it.

**Comment by sigurdhasle** [comment]
I am sorry if you consider me a rude asshole. I opened a new issue because I was not aware that I could comment in a closed one. I am just frustrated that I cannot use the small caps: it still doesn't work for me. Do you have any idea why?

I have downloaded and installed the files again today – they should not be old files.. The small caps Æ still looks like a lowercase æ – both in MainType and LibreOffice.

**Comment by ctrlcctrlv** [comment]
Try the files in [`№19`](https://github.com/indestructible-type/Besley/tree/%E2%84%9619) branch.
